(in-package #:org.shirakumo.raster)

(deftype sdf ()
  '(function (index index) single-float))

(defun rectangle (x y w h)
  (let ((x (float x 0f0)) (y (float y 0f0))
        (w (float w 0f0)) (h (float h 0f0)))
    (lambda (nx ny)
      (declare (type index nx ny))
      (let ((dx (- (abs (- nx x)) w))
            (dy (- (abs (- ny y)) h)))
        (+ (min 0f0 (max dx dy))
           (sqrt (+ (expt (max dx 0f0) 2)
                    (expt (max dy 0f0) 2))))))))

(defun ellipse (x y w h)
  (let ((x (float x 0f0)) (y (float y 0f0))
        (w (/ 2f0 (float w 0f0))) (h (/ 2f0 (float h 0f0))))
    (lambda (nx ny)
      (declare (type index nx ny))
      (sqrt (+ (expt (* (- nx x) w) 2)
               (expt (* (- ny y) h) 2))))))

(defun subtract (a b)
  (declare (type sdf a b))
  (lambda (x y)
    (declare (type index x y))
    (max (funcall a x y)
         (- (funcall b x y)))))

(defun combine (a b)
  (declare (type sdf a b))
  (lambda (x y)
    (declare (type index x y))
    (min (funcall a x y)
         (funcall b x y))))

(defun intersect (a b)
  (declare (type sdf a b))
  (lambda (x y)
    (declare (type index x y))
    (let ((a (funcall a x y))
          (b (funcall b x y)))
      (max (min a b) (- (max a b))))))
